sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jjdltorre/docker-react -f Dockerfile.dev .

script:
  # - docker run jjdltorre/docker-react npm run test -- --coverage
  - docker run -e CI=true jjdltorre/docker-react npm run test
