sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jjdltorre/docker-react -f Dockerfile.dev .

script:
  # - docker run jjdltorre/docker-react npm run test -- --coverage
  - docker run -e CI=true jjdltorre/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "S3-bucket-name"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key:
    secure: "$AWS_SECRET_KEY"
